name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: Taure/erlang-ci/.github/workflows/ci.yml@v2
    permissions:
      contents: write
      pull-requests: write
    with:
      enable-audit: false
      enable-summary: true
    secrets: inherit
